chore: refactor common-functions

diff --git a/common-functions b/common-functions
--- a/common-functions
+++ b/common-functions
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-# Common functions for bash tools
-# Based on Google Shell Style Guide
+# Common functions for bash tools based on Google Shell Style Guide
 
-# Check bash version
+##----Check bash version------------------------------------------------------------------------------------------------------------
+
 if [[ "$BASH_VERSION" == 0* ]] || [[ "$BASH_VERSION" == 1* ]] || [[ "$BASH_VERSION" == 2* ]] || [[ "$BASH_VERSION" == 3* ]]; then
   echo "Bash version is too low. Consider upgrading to bash newer than $BASH_VERSION"
   if uname | grep -iq Darwin; then
@@ -12,24 +12,45 @@ if [[ "$BASH_VERSION" == 0* ]] || [[ "$BASH_VERSION" == 1* ]] || [[ "$BASH_VERSI
   exit 9
 fi
 
-# Formatting using tput
-readonly COLOR_RED=$(tput setaf 1)
-readonly COLOR_GREEN=$(tput setaf 2)
-readonly COLOR_YELLOW=$(tput setaf 3)
-readonly COLOR_BLUE=$(tput setaf 4)
-readonly COLOR_PURPLE=$(tput setaf 5)
-readonly COLOR_CYAN=$(tput setaf 6)
-readonly FORMAT_BOLD=$(tput bold)
-readonly FORMAT_RESET=$(tput sgr0)
+# Set terminal type for proper color support
+export TERM=xterm-256color
+shopt -s extglob
 
-# Display line constants
-readonly DISPLAY_LINE_NO_ICON='display_line.no_icon'
-readonly DISPLAY_LINE_SILENT_BELL='display_line.silent_bell'
-readonly DISPLAY_LINE_PREPEND_NL='display_line.line_prepend_nl'
-readonly DISPLAY_LINE_PREPEND_CR='display_line.line_prepend_cr'
-readonly DISPLAY_LINE_PREPEND_TAB='display_line.line_prepend_tab'
-readonly DISPLAY_LINE_APPEND_NULL='display_line.line_append_null'
-readonly DISPLAY_LINE_APPEND_NL='display_line.line_append_nl'
+##----Formatting------------------------------------------------------------------------------------------------------------
+
+styler() {
+  case "$1" in
+  font | text | FONT | TEXT)
+    case "$2" in
+    black | BLACK) tput setaf 0 ;;
+    red | RED) tput setaf 1 ;;
+    green | GREEN) tput setaf 2 ;;
+    yellow | YELLOW) tput setaf 3 ;;
+    blue | BLUE) tput setaf 4 ;;
+    purple | PURPLE) tput setaf 5 ;;
+    cyan | CYAN) tput setaf 6 ;;
+    white | WHITE) tput setaf 7 ;;
+    *) tput setaf 9 ;;
+    esac
+    ;;
+  bg | background | BG | BACKGROUND)
+    case "$2" in
+    reset | REST) tput sgr0 ;;
+    black | BLACK) tput setab 0 ;;
+    red | RED) tput setab 1 ;;
+    green | GREEN) tput setab 2 ;;
+    yellow | YELLOW) tput setab 3 ;;
+    blue | BLUE) tput setab 4 ;;
+    purple | PURPLE) tput setab 5 ;;
+    cyan | CYAN) tput setab 6 ;;
+    white | WHITE) tput setab 7 ;;
+    *) tput setab 9 ;;
+    esac
+    ;;
+  bold | BOLD) tput bold ;;
+  reset | REST) tput sgr0 ;;
+  esac
+}
 
 # Icons
 readonly ICON_INFO='☞'
@@ -39,80 +60,159 @@ readonly ICON_ERROR='✗'
 readonly ICON_DEBUG=''
 readonly ICON_PROMPT='↳'
 
-# Display line with formatting options
-display_line() {
-  local _color="$1"
-  shift
-  local _icon="$1 "
-  shift
+readonly LOADING_ANIMATION=("⠇" "⠋" "⠙" "⠸" "⠴" "⠦")
+readonly LOADING_ANIMATION_FRAME_INTERVAL=0.15
+
+##----Display line------------------------------------------------------------------------------------------------------------
+
+log_message() {
+  function _text_format() {
+    local _color_value="$1"
+    shift
+    local _pattern="$1"
+    shift
+    local _text
+    # shellcheck disable=SC2059
+    _text=$(printf -- "$_pattern" "$@")
+    _text=${_text//<b>/$(styler bold)${_color_value}}
+    _text=${_text//<\/b>/$(styler reset)${_color_value}}
+    _text=${_text//<u>/$(tput smul)${_color_value}}
+    _text=${_text//<\/u>/$(tput rmul)${_color_value}}
+    _text=${_text//<code>/$(styler bg "CYAN")$(styler text "BLACK")}
+    _text=${_text//<\/code>/$(styler reset)${_color_value}}
+    echo -e "$_text"
+  }
+  local _color_value=""
+  local _icon=""
   local _line_prepend=""
   local _line_append="\n"
-  while true; do
-    case $1 in
-    "display_line.no_icon")
-      _icon=""
+  local _text
+  local _status=""
+  while [[ "${1:-}" != "" ]]; do
+    case ${1} in
+    -c | --color)
+      shift
+      _color_value="$(styler text "$1")"
       ;;
-    "display_line.silent_bell")
-      _line_prepend="\a\r"
+    -i | --icon)
+      shift
+      _icon="$1"
       ;;
-    "display_line.line_prepend_nl")
-      _line_prepend="\n"
+    -p | --prepend)
+      shift
+      _line_prepend="$_line_prepend$1"
       ;;
-    "display_line.line_prepend_cr")
-      _line_prepend="\r"
+    -b | --bell)
+      _line_prepend="$_line_prepend\a"
       ;;
-    "display_line.line_prepend_tab")
-      _line_prepend="\t"
+    -r | --reset)
+      _line_prepend="\r$_line_prepend"
       ;;
-    "display_line.line_append_nl")
-      _line_append="\n"
-      ;;
-    "display_line.line_append_null")
+    -o | --one-line)
       _line_append=""
       ;;
-    *)
-      break
+    -s | --status)
+      shift
+      _status="$1"
       ;;
+    *) break ;;
     esac
     shift
   done
-  local _text_pattern="$1"
-  shift
-  local _text
   # shellcheck disable=SC2059
-  _text=$(printf "$_text_pattern" "$@")
-  _text=${_text//<b>/${FORMAT_BOLD}${_color}}
-  _text=${_text//<\/b>/${FORMAT_RESET}${_color}}
-  _text=${_text//<u>/$(tput smul)${_color}}
-  _text=${_text//<\/u>/$(tput rmul)${_color}}
-  echo -e -n "${_line_prepend}${_color}${_icon}${_text}${FORMAT_RESET}${_line_append}"
+  _text="$(_text_format "$_color_value" "$@")"
+  if [[ -n "$_icon" ]]; then
+    _text="$(_text_format "$_color_value" " <b>%s</b> %s" "$_icon" "$_text")"
+  fi
+  if [[ -n "$_status" ]]; then
+    local _raw_bytes
+    _raw_bytes="$(echo -n "${_text//$'\e'[\[(]*([0-9;])[@-n]/}" | wc -c | tr -d ' ')"
+    local _text_bytes
+    _text_bytes="$(echo -n "$_text" | wc -c | tr -d ' ')"
+    local _text_chars
+    _text_chars="$(echo -n "$_text" | wc -m | tr -d ' ')"
+    local _padding=$((64 + (_text_bytes - _text_chars) + (_text_bytes - _raw_bytes)))
+    _text="$(_text_format "$_color_value" "%-*s [<b>%s</b>]" "$_padding" "$_text" "$_status")"
+  fi
+  echo -e -n "${_line_prepend}${_color_value}${_text}${_line_append}$(styler reset)"
 }
 
-# Logging functions
+prepare_log_message() {
+  local _color="$1"
+  shift
+  local _icon="$1"
+  shift
+  while [[ "${1:-}" != "" ]]; do
+    case ${1} in
+    -c | --color)
+      shift
+      _color="$1"
+      ;;
+    -i | --icon)
+      shift
+      _icon="$1"
+      ;;
+    *) break ;;
+    esac
+    shift
+  done
+  log_message --color "$_color" --icon "$_icon" "$@"
+}
+
 log_info() {
-  display_line "$COLOR_BLUE" "$ICON_INFO" "$@"
+  prepare_log_message "CYAN" "$ICON_INFO" "$@"
 }
 
 log_success() {
-  display_line "$COLOR_GREEN" "$ICON_SUCCESS" "$@"
+  prepare_log_message "GREEN" "$ICON_SUCCESS" "$@"
 }
 
 log_warning() {
-  display_line "$COLOR_YELLOW" "$ICON_WARNING" "$@"
+  prepare_log_message "BLUE" "$ICON_WARNING" "$@"
 }
 
 log_error() {
-  display_line "$COLOR_RED" "$ICON_ERROR" "$@"
+  prepare_log_message "RED" "$ICON_ERROR" "$@"
 }
 
 log_debug() {
   if [[ "${DEBUG:-0}" == "1" || "${debug:-0}" == "1" ]]; then
-    display_line "$COLOR_PURPLE" "$ICON_DEBUG" "$@"
+    prepare_log_message "PURPLE" "$ICON_DEBUG" "$@"
   fi
 }
 
+log_title() {
+  local _title="$1"
+  local _version="${2:-}"
+  local _title_text
+  if [[ -n "$_version" ]]; then
+    _title_text="${_title} v${_version}"
+  else
+    _title_text="${_title}"
+  fi
+
+  # Calculate padding to center the title
+  local _title_length=${#_title_text}
+  local _total_width=64
+  if [[ "$_title_length" -gt "$_total_width" ]]; then
+    _total_width=$((_title_length + 4))
+  fi
+  if [[ $((_title_length % 2)) -eq 1 ]]; then
+    _total_width="$((_total_width - 1))"
+  fi
+  local _padding=$(((_total_width - _title_length) / 2))
+
+  log_message --color "WHITE" "<b>╔%s╗</b>" "$(printf "═%.0s" $(seq 1 1 $_total_width))"
+  log_message --color "WHITE" "<b>║%*s$(styler text "YELLOW")%s%*s$(styler text "WHITE")║</b>" $_padding "" "$_title_text" $_padding ""
+  log_message --color "WHITE" "<b>╚%s╝</b>" "$(printf "═%.0s" $(seq 1 1 $_total_width))"
+}
+
+log_header() {
+  log_message --color "PURPLE" "<b>%s</b>" "$1"
+}
+
 log_usage_line() {
-  echo -e "${FORMAT_BOLD}${COLOR_GREEN}Usage:${COLOR_BLUE} $*${FORMAT_RESET}"
+  log_message --color "PURPLE" "<b>Usage</b> <code>$*</code>"
 }
 
 log_usage_options_line() {
@@ -120,19 +220,11 @@ log_usage_options_line() {
   shift
   local parameters
   parameters="$(printf "%s, " "$@")"
-  display_line "" "" "$DISPLAY_LINE_NO_ICON" "  ${FORMAT_BOLD}${COLOR_CYAN}%-*s${FORMAT_RESET}${COLOR_CYAN} %s" "30" "${parameters::-2}" "$description"
+  log_message "  <b>%-*s</b> %s" "30" "${parameters::-2}" "$description"
 }
 
 log_usage_example_line() {
-  display_line "  \$" "$COLOR_BLUE" "$@"
-}
-
-log_prompt() {
-  if [[ "$#" -gt "1" ]]; then
-    display_line "$COLOR_YELLOW" "$ICON_PROMPT" "$DISPLAY_LINE_APPEND_NULL" "%s [%s]: " "$@"
-  else
-    display_line "$COLOR_YELLOW" "$ICON_PROMPT" "$DISPLAY_LINE_APPEND_NULL" "%s: " "$@"
-  fi
+  log_message --color "CYAN" --icon " \$" "<code>%s</code>" "$@"
 }
 
 # Die with error message
@@ -141,71 +233,137 @@ die() {
   exit 1
 }
 
+##----Loading animation------------------------------------------------------------------------------------------------------------
+
+play_loading_animation_loop() {
+  while [ $# -gt 0 ]; do
+    case $1 in
+    -t | --time)
+      shift
+      loading_animation_timer="$1"
+      ;;
+    -m | --message)
+      shift
+      loading_animation_message="$1"
+      ;;
+    esac
+    shift
+  done
+  (
+    _step=0
+    while true; do
+      for _frame in "${LOADING_ANIMATION[@]}"; do
+        if [[ "$loading_animation_message" != "" ]]; then
+          log_message --color "CYAN" --one-line --icon "$_frame" "$loading_animation_message"
+          sleep "$LOADING_ANIMATION_FRAME_INTERVAL"
+        else
+          log_message --color "CYAN" --one-line "waiting %s" "$(echo "$loading_animation_timer - $_step" | bc -z)"
+          sleep "1"
+        fi
+        _step="$((_step + 1))"
+        printf "\r"
+      done
+    done
+  ) &
+  loading_animation_pid=$!
+}
+
+kill_loading_animation_loop() {
+  if [[ -n "${loading_animation_pid:-}" ]]; then
+    kill "$loading_animation_pid" &>/dev/null
+    printf "\r%100s\r$(styler reset)" ""
+    code=0
+    status=""
+    while [ $# -gt 0 ]; do
+      case $1 in
+      -c | --code)
+        shift
+        code="$1"
+        ;;
+      -s | --status)
+        shift
+        status="$1"
+        ;;
+      -m | --message)
+        shift
+        loading_animation_message="$1"
+        ;;
+      esac
+      shift
+    done
+    if [[ "$loading_animation_message" != "" ]]; then
+      if [[ "$code" -gt "0" ]]; then
+        log_error --status "$status" "$loading_animation_message"
+      elif [[ "$code" -lt "0" ]]; then
+        log_warning --status "$status" "$loading_animation_message"
+      else
+        log_success --status "$status" "$loading_animation_message"
+      fi
+    fi
+    loading_animation_pid=""
+    loading_animation_message=""
+    loading_animation_timer=""
+  fi
+}
+
+wait_moment() {
+  play_loading_animation_loop --time "$RETRY_INTERVAL"
+  sleep "$RETRY_INTERVAL"
+  kill_loading_animation_loop --code 0
+}
+
+trap "kill_loading_animation_loop;exit" SIGINT
+trap "kill_loading_animation_loop;exit" EXIT
+
+##----IO------------------------------------------------------------------------------------------------------------
+
+prompt_input() {
+  # prepare
+  local _var_name="$1"
+  shift
+  local _prompt_text="$1"
+  shift
+  local _default_value="${1:-}"
+  shift
+  # options
+  local _options
+  _options="$(printf "<b>%s</b>," "$@")"
+  local _message
+  if [[ -n "$_options" ]]; then
+    _message="$(log_message --color "YELLOW" --icon "$ICON_PROMPT" --one-line "%s [%s]: " "$_prompt_text" "${_options::-1}")"
+  else
+    _message="$(log_message --color "YELLOW" --icon "$ICON_PROMPT" --one-line "%s: " "$_prompt_text")"
+  fi
+
+  # get
+  local _value
+  read -r -p "$_message" -e -i "$_default_value" _value
+  if [[ -z "$_value" ]]; then
+    _value="$_default_value"
+  fi
+
+  # set
+  eval "$_var_name=\"$_value\""
+}
+
+confirm_or_exit() {
+  local _message="$1"
+  local _default_value="${2:-}"
+  local _response="z"
+
+  while [[ ! "$_response" =~ ^[YyNn]?$ ]]; do
+    prompt_input _response "$_message" "$_default_value" "Y" "y" "N" "n"
+    [[ "$_response" =~ ^[Yy]?$ ]] && break
+  done
+}
+
+##----Checking------------------------------------------------------------------------------------------------------------
+
 # Check if command exists
 command_exists() {
   command -v "$1" >/dev/null 2>&1
 }
 
-# Prompt for input
-prompt_input() {
-  local var_name="$1"
-  local prompt_text="$2"
-  local default_value="${3:-}"
-  local current_value="${4:-}"
-
-  local value
-  if [[ -n "$current_value" ]]; then
-    log_prompt "$prompt_text" "$current_value"
-    read -r value
-    if [[ -z "$value" ]]; then
-      value="$current_value"
-    fi
-  else
-    log_prompt "$prompt_text"
-    read -r value
-    if [[ -z "$value" && -n "$default_value" ]]; then
-      value="$default_value"
-    fi
-  fi
-
-  eval "$var_name=\"$value\""
-}
-
-# Log title
-log_title() {
-  local title="$1"
-  local version="${2:-""}"
-  local title_text
-  if [[ -n "$version" ]]; then
-    title_text="${title} v${version}"
-  else
-    title_text="${title}"
-  fi
-
-  # Calculate padding to center the title
-  local title_length=${#title_text}
-  local total_width=64
-  if [[ "$total_width" -lt "$title_length" ]]; then
-    total_width=$((title_length + 4))
-  fi
-  local padding=$(((total_width - title_length) / 2))
-
-  # Generate top and bottom borders
-
-  border="$(printf "%*s" "$total_width" "" | tr " " "═")"
-  printf "${FORMAT_BOLD}${COLOR_CYAN}╔%s╗${FORMAT_RESET}\n" "$border"
-  printf "${FORMAT_BOLD}${COLOR_CYAN}║${FORMAT_RESET}%*s${FORMAT_BOLD}${COLOR_YELLOW}%s${FORMAT_RESET}%*s${FORMAT_BOLD}${COLOR_CYAN}║${FORMAT_RESET}\n" $padding "" "$title_text" $padding ""
-  printf "${FORMAT_BOLD}${COLOR_CYAN}╚%s╝${FORMAT_RESET}\n" "$border"
-}
-
-# Show script title
-show_title() {
-  local script_name="$1"
-  local version="${2:-1.0.0}"
-  echo "${COLOR_CYAN}## $script_name v$version ##${FORMAT_RESET}"
-}
-
-# Check dependencies
 check_dependencies() {
   local deps=("$@")
   local missing_deps=()
@@ -217,26 +375,8 @@ check_dependencies() {
   done
 
   if [[ ${#missing_deps[@]} -gt 0 ]]; then
-    missing_items="$(printf "${FORMAT_BOLD}${COLOR_RED}%s${FORMAT_RESET}${COLOR_RED}, " "${missing_deps[@]}")"
+    missing_items="$(printf "<b>%s</b>, " "${missing_deps[@]}")"
     die "Missing dependencies: %s. Please install them and try again." "${missing_items::-2}"
-  fi
-}
-
-# Removed duplicate prompt_input function
-
-# Confirm action
-confirm() {
-  local message="$1"
-  local default="${2:-n}"
-
-  if [[ "$default" == "y" ]]; then
-    log_prompt "$message" "Y/n"
-    read -r response
-    [[ "$response" =~ ^[Yy]?$ ]]
-  else
-    log_prompt "$message" "y/N"
-    read -r response
-    [[ "$response" =~ ^[Yy]$ ]]
   fi
 }
 
@@ -268,11 +408,11 @@ validate_domain() {
 validate_wp_directory() {
   local wp_dir="$1"
   if [[ ! -d "$wp_dir" ]]; then
-    log_error "WordPress directory does not exist: $wp_dir"
+    log_error "WordPress directory <u>$wp_dir</u> does not exist"
     return 1
   fi
   if [[ ! -f "$wp_dir/wp-config.php" ]]; then
-    log_error "Not a valid WordPress directory (wp-config.php not found): $wp_dir"
+    log_error "Given directory <u>$wp_dir</u> is not a valid WordPress installation (wp-config.php not found)"
     return 1
   fi
   return 0
@@ -308,22 +448,4 @@ validate_positive_number() {
     return 1
   fi
   return 0
-}
-
-# Main function wrapper
-main() {
-  # Check if common-functions exists
-  if [[ ! -f "$(dirname "$0")/common-functions" ]]; then
-    echo "Downloading common-functions from GitHub..."
-    if ! curl -fsSL https://raw.githubusercontent.com/Flower7C3/bash-tools/master/common-functions -o "$(dirname "$0")/common-functions"; then
-      echo "Failed to download common-functions"
-      exit 1
-    fi
-  fi
-
-  # Source common functions
-  source "$(dirname "$0")/common-functions"
-
-  # Call the actual main function
-  "$@"
 }
diff --git a/jpg-to-mp4-convert b/jpg-to-mp4-convert
--- a/jpg-to-mp4-convert
+++ b/jpg-to-mp4-convert
@@ -29,15 +29,15 @@ show_usage() {
   echo ""
   echo "Convert JPG images to MP4 video"
   echo ""
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Options:${FORMAT_RESET}"
+  log_header "Options"
   log_usage_options_line "Source directory containing JPG images" "-s" "--source DIR"
   log_usage_options_line "Frame rate for output video (default: $DEFAULT_FRAMERATE)" "-f" "--framerate FPS"
   log_usage_options_line "Show this help message" "-h" "--help"
   echo ""
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Examples:${FORMAT_RESET}"
+  log_header "Examples"
   log_usage_example_line "$0 --source /path/to/images"
   log_usage_example_line "$0 -s /path/to/images -f 30"
-  log_usage_example_line "$0                    # Will prompt for source directory"
+  log_usage_example_line "$0 ${FORMAT_RESET}Will prompt for source directory"
   exit 0
 }
 
@@ -75,55 +75,48 @@ parse_arguments() {
 # Function to prompt for directory
 prompt_for_directory() {
   while true; do
-    log_prompt "Enter source directory path"
-    read -r source_dir
-    if [ -z "$source_dir" ]; then
+    prompt_input '_source_dir' "Enter source directory path" ""
+    if [ -z "$_source_dir" ]; then
       log_error "Directory path cannot be empty"
       continue
     fi
-
-    # Expand tilde and resolve relative paths
-    source_dir=$(eval echo "$source_dir")
-
-    if ! validate_directory "$source_dir"; then
+    if ! verify_directory "$_source_dir"; then
       continue
     fi
-
-    # Check if directory contains JPG files
-    jpg_count=$(find "$source_dir" -maxdepth 1 -name "*.JPG" -o -name "*.jpg" | wc -l)
-    if [ "$jpg_count" -eq 0 ]; then
-      log_error "No JPG files found in directory '$source_dir'"
-      continue
-    fi
-
-    log_info "Found $jpg_count JPG files in '$source_dir'"
     break
   done
 }
 
 # Function to verify directory and JPG files
 verify_directory() {
-  local dir="$1"
+  local _source_dir="$1"
 
-  if ! validate_directory "$dir"; then
+  if [[ "$_source_dir" != */ ]]; then
+    _source_dir="${_source_dir}/"
+  fi
+
+  if ! validate_directory "$_source_dir"; then
     return 1
   fi
 
   # Check if directory contains JPG files
-  local jpg_count=$(find "$dir" -maxdepth 1 -name "*.JPG" -o -name "*.jpg" | wc -l)
-  if [ "$jpg_count" -eq 0 ]; then
-    log_error "No JPG files found in directory '$dir'"
-    return 1
+  local _jpg_count
+  _jpg_count=$(find "$_source_dir" -maxdepth 1 -name "*.JPG" -o -name "*.jpg" | wc -l | tr -d ' ')
+  if [ "$_jpg_count" -eq 0 ]; then
+    die "No JPG files found in <u>%s</u> directory" "$_source_dir"
   fi
 
-  log_info "Found $jpg_count JPG files in '$dir'"
+  log_info "Found <b>%s</b> JPG files in <u>%s</u> directory" "$_jpg_count" "$_source_dir"
+  source_dir="$_source_dir"
   return 0
 }
-
 
 # Main function
 converter_main() {
   log_title "JPG to MP4 Converter"
+
+  # Check dependencies
+  check_dependencies ffmpeg
 
   # Parse command line arguments
   parse_arguments "$@"
@@ -132,42 +125,22 @@ converter_main() {
   if [ -z "$source_dir" ]; then
     prompt_for_directory
   else
-    # Expand tilde and resolve relative paths
-    source_dir=$(eval echo "$source_dir")
-
     if ! verify_directory "$source_dir"; then
       exit 1
     fi
   fi
 
-  # Check dependencies
-  check_dependencies ffmpeg
+  cd "$source_dir" || die "Cannot access <u>$source_dir</u> directory"
 
-  # Change to source directory
-  cd "$source_dir" || die "Cannot access directory '$source_dir'"
+  confirm_or_exit "Convert those files to MP4 video with <b>$framerate</b> framerate?"
 
-  # Create output filename with timestamp
-  output_file="video_$(date +%Y%m%d_%H%M%S).mp4"
-
-  log_info "Converting JPG images to MP4 video..."
-  log_info "Source directory: $source_dir"
-  log_info "Framerate: $framerate fps"
-  log_info "Output file: $output_file"
-
-  # Get list of JPG files and sort them
-  jpg_files=($(find "$source_dir" -maxdepth 1 -name "*.JPG" -o -name "*.jpg" | sort))
-
-  if [ ${#jpg_files[@]} -eq 0 ]; then
-    die "No JPG files found in directory '$source_dir'"
-  fi
-
-  # Create a temporary directory for renamed files
   temp_dir="/tmp/animate_jpg_$$"
-  mkdir -p "$temp_dir"
-
-  # Get the extension from the first file
+  jpg_files=($(find "$source_dir" -maxdepth 1 -name "*.JPG" -o -name "*.jpg" | sort))
   first_file=$(basename "${jpg_files[0]}")
   extension="${first_file##*.}"
+  output_file="video_$(date +%Y%m%d_%H%M%S).mp4"
+
+  mkdir -p "$temp_dir"
 
   # Rename files to sequential pattern for ffmpeg
   for i in "${!jpg_files[@]}"; do
@@ -175,15 +148,11 @@ converter_main() {
     cp "${jpg_files[$i]}" "$temp_dir/$new_name"
   done
 
-  # Run ffmpeg conversion
-  ffmpeg -framerate "$framerate" -i "$temp_dir/img%05d.$extension" -vf format=yuv420p "$output_file"
-
-  # Cleanup temporary directory
-  rm -rf "$temp_dir"
-
-  if [ $? -eq 0 ]; then
-    log_success "Video created: $output_file"
+  if ffmpeg -framerate "$framerate" -i "$temp_dir/img%05d.$extension" -vf format=yuv420p "$output_file"; then
+    rm -rf "$temp_dir"
+    log_success --status "$source_dir$output_file" "Video created"
   else
+    rm -rf "$temp_dir"
     die "Video conversion failed"
   fi
 }
diff --git a/map-download b/map-download
--- a/map-download
+++ b/map-download
@@ -29,7 +29,7 @@ show_usage() {
   echo ""
   echo "Download maps from GeoApify or OpenStreetMap"
   echo ""
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Options:${FORMAT_RESET}"
+  log_header "Options"
   log_usage_options_line "Map provider: geoapify, osm (default: $DEFAULT_PROVIDER)" "-p" "--provider PROVIDER"
   log_usage_options_line "Map zoom level (default: $DEFAULT_ZOOM)" "-z" "--zoom ZOOM"
   log_usage_options_line "Map type: standard, cycle (default: $DEFAULT_MAP_TYPE)" "-t" "--type TYPE"
@@ -44,17 +44,14 @@ show_usage() {
   log_usage_options_line "Debug output" "-d" "--debug"
   log_usage_options_line "Show this help message" "-h" "--help"
   echo ""
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Examples:${FORMAT_RESET}"
-  echo "  # OSM map with bounding box"
+  log_header "Examples"
+  echo " OSM map with bounding box"
   log_usage_example_line "$0 --provider osm --bounds \"20.2008,49.9817,20.4651,50.0836\" --zoom 15"
-  echo ""
-  echo "  # GeoApify map with center point"
+  echo " GeoApify map with center point"
   log_usage_example_line "$0 --provider geoapify --center \"50.0326,20.0000\" --zoom 15 --api-key YOUR_KEY"
-  echo ""
-  echo "  # GeoApify map with markers"
+  echo " GeoApify map with markers"
   log_usage_example_line "$0 --provider geoapify --center \"50.0326,20.0000\" --markers \"lonlat:20.0000,50.0326;type:circle;color:red\" --api-key YOUR_KEY"
-  echo ""
-  echo "  # OSM cycle map"
+  echo " OSM cycle map"
   log_usage_example_line "$0 --provider osm --type cycle --bounds \"20.2008,49.9817,20.4651,50.0836\""
   exit 0
 }
@@ -83,25 +80,25 @@ center_lng=""
 api_key=""
 markers=""
 verbose=0
-debug=0
+DEBUG=0
 
 # Function to validate coordinates
 validate_coordinates() {
-  local lat="$1"
-  local lng="$2"
+  local _lat="$1"
+  local _lng="$2"
 
-  if ! [[ "$lat" =~ ^-?[0-9]+\.?[0-9]*$ ]] || ! [[ "$lng" =~ ^-?[0-9]+\.?[0-9]*$ ]]; then
-    log_error "Invalid coordinate format: $lat, $lng"
+  if ! [[ "$_lat" =~ ^-?[0-9]+\.?[0-9]*$ ]] || ! [[ "$_lng" =~ ^-?[0-9]+\.?[0-9]*$ ]]; then
+    log_error "Invalid coordinate format: $_lat, $_lng"
     return 1
   fi
 
-  if (($(echo "$lat < -90 || $lat > 90" | bc -l))); then
-    log_error "Latitude must be between -90 and 90: $lat"
+  if (($(echo "$_lat < -90 || $_lat > 90" | bc -l))); then
+    log_error "Latitude must be between -90 and 90: $_lat"
     return 1
   fi
 
-  if (($(echo "$lng < -180 || $lng > 180" | bc -l))); then
-    log_error "Longitude must be between -180 and 180: $lng"
+  if (($(echo "$_lng < -180 || $_lng > 180" | bc -l))); then
+    log_error "Longitude must be between -180 and 180: $_lng"
     return 1
   fi
 
@@ -110,21 +107,21 @@ validate_coordinates() {
 
 # Function to validate bounding box
 validate_bounding_box() {
-  local w="$1"
-  local s="$2"
-  local e="$3"
-  local n="$4"
+  local _w="$1"
+  local _s="$2"
+  local _e="$3"
+  local _n="$4"
 
-  if ! validate_coordinates "$s" "$w" || ! validate_coordinates "$n" "$e"; then
+  if ! validate_coordinates "$_s" "$_w" || ! validate_coordinates "$_n" "$_e"; then
     return 1
   fi
 
-  if (($(echo "$w >= $e" | bc -l))); then
+  if (($(echo "$_w >= $_e" | bc -l))); then
     log_error "West coordinate must be less than East coordinate"
     return 1
   fi
 
-  if (($(echo "$s >= $n" | bc -l))); then
+  if (($(echo "$_s >= $_n" | bc -l))); then
     log_error "South coordinate must be less than North coordinate"
     return 1
   fi
@@ -145,46 +142,46 @@ download_osm_map() {
   log_info "Downloading OSM map..."
 
   # Convert coordinates to tile coordinates
-  local xtile_min xtile_max ytile_min ytile_max
+  local _xtile_min _xtile_max _ytile_min _ytile_max
 
   # Replace comma with dot for bc calculations
-  local geo_long_w_bc="${geo_long_w//,/.}"
-  local geo_lat_s_bc="${geo_lat_s//,/.}"
-  local geo_long_e_bc="${geo_long_e//,/.}"
-  local geo_lat_n_bc="${geo_lat_n//,/.}"
+  local _geo_long_w_bc="${geo_long_w//,/.}"
+  local _geo_lat_s_bc="${geo_lat_s//,/.}"
+  local _geo_long_e_bc="${geo_long_e//,/.}"
+  local _geo_lat_n_bc="${geo_lat_n//,/.}"
 
   # Calculate tile coordinates
-  xtile_min=$(echo "scale=0; (($geo_long_w_bc + 180) / 360 * 2^$zoom)" | bc)
-  xtile_max=$(echo "scale=0; (($geo_long_e_bc + 180) / 360 * 2^$zoom)" | bc)
-  ytile_min=$(echo "scale=0; ((1 - log(tan($geo_lat_n_bc * pi() / 180) + 1 / cos($geo_lat_n_bc * pi() / 180)) / pi()) / 2 * 2^$zoom)" | bc -l)
-  ytile_max=$(echo "scale=0; ((1 - log(tan($geo_lat_s_bc * pi() / 180) + 1 / cos($geo_lat_s_bc * pi() / 180)) / pi()) / 2 * 2^$zoom)" | bc -l)
+  xtile_min=$(echo "scale=0; (($_geo_long_w_bc + 180) / 360 * 2^$zoom)" | bc)
+  xtile_max=$(echo "scale=0; (($_geo_long_e_bc + 180) / 360 * 2^$zoom)" | bc)
+  ytile_min=$(echo "scale=0; ((1 - log(tan($_geo_lat_n_bc * pi() / 180) + 1 / cos($_geo_lat_n_bc * pi() / 180)) / pi()) / 2 * 2^$zoom)" | bc -l)
+  ytile_max=$(echo "scale=0; ((1 - log(tan($_geo_lat_s_bc * pi() / 180) + 1 / cos($_geo_lat_s_bc * pi() / 180)) / pi()) / 2 * 2^$zoom)" | bc -l)
 
   log_debug "Tile coordinates: x=$xtile_min-$xtile_max, y=$ytile_min-$ytile_max"
 
   # Calculate tile amounts
-  local xtile_amount=$((xtile_max - xtile_min + 1))
-  local ytile_amount=$((ytile_max - ytile_min + 1))
-  local tile_amount=$((xtile_amount * ytile_amount))
+  local _xtile_amount=$((_xtile_max - _xtile_min + 1))
+  local _ytile_amount=$((_ytile_max - _ytile_min + 1))
+  local _tile_amount=$((_xtile_amount * _ytile_amount))
 
-  log_info "Downloading $tile_amount tiles..."
+  log_info "Downloading $_tile_amount tiles..."
 
   # Create temporary directory
-  local temp_dir="/tmp/map_download_$$"
-  mkdir -p "$temp_dir"
+  local _temp_dir="/tmp/map_download_$$"
+  mkdir -p "$_temp_dir"
 
   # Download tiles
-  local tile_index=0
+  local _tile_index=0
   for ((xtile = xtile_min; xtile <= xtile_max; xtile++)); do
     for ((ytile = ytile_min; ytile <= ytile_max; ytile++)); do
-      local url
-      local tile_file="$temp_dir/tile_${xtile}_${ytile}.png"
+      local _url
+      local _tile_file="$_temp_dir/tile_${xtile}_${ytile}.png"
 
       case "$map_type" in
       "standard")
-        url="http://a.tile.openstreetmap.org/$zoom/$xtile/$ytile.png"
+        _url="http://a.tile.openstreetmap.org/$zoom/$xtile/$ytile.png"
         ;;
       "cycle")
-        url="http://a.tile.opencyclemap.org/cycle/$zoom/$xtile/$ytile.png"
+        _url="http://a.tile.opencyclemap.org/cycle/$zoom/$xtile/$ytile.png"
         ;;
       *)
         log_error "Unsupported map type: $map_type"
@@ -192,18 +189,18 @@ download_osm_map() {
         ;;
       esac
 
-      local progress=$((100 * tile_index / tile_amount))
+      local _progress=$((100 * _tile_index / _tile_amount))
       if [[ "$verbose" == "1" ]]; then
-        log_info "Downloading tile $((tile_index + 1))/$tile_amount ($progress%) - $url"
+        log_info "Downloading tile $((_tile_index + 1))/$_tile_amount ($_progress%) - $_url"
       else
-        printf "\rDownloading tiles: %d/%d (%d%%)" $((tile_index + 1)) "$tile_amount" "$progress"
+        printf "\rDownloading tiles: %d/%d (%d%%)" $((_tile_index + 1)) "$_tile_amount" "$_progress"
       fi
 
-      if ! curl -s "$url" -o "$tile_file"; then
-        log_warning "Failed to download tile: $url"
+      if ! curl -s "$_url" -o "$_tile_file"; then
+        log_warning "Failed to download tile: $_url"
       fi
 
-      ((tile_index++))
+      ((_tile_index++))
     done
   done
 
@@ -219,11 +216,11 @@ download_osm_map() {
   # Combine tiles using ImageMagick
   local temp_files=()
   for ((xtile = xtile_min; xtile <= xtile_max; xtile++)); do
-    local row_file="$temp_dir/row_${xtile}.png"
+    local row_file="$_temp_dir/row_${xtile}.png"
     local row_files=()
 
     for ((ytile = ytile_min; ytile <= ytile_max; ytile++)); do
-      local tile_file="$temp_dir/tile_${xtile}_${ytile}.png"
+      local tile_file="$_temp_dir/tile_${xtile}_${ytile}.png"
       if [[ -f "$tile_file" ]]; then
         row_files+=("$tile_file")
       fi
@@ -244,7 +241,7 @@ download_osm_map() {
   fi
 
   # Cleanup
-  rm -rf "$temp_dir"
+  rm -rf "$_temp_dir"
 }
 
 # Function to download GeoApify map
@@ -359,7 +356,7 @@ parse_arguments() {
       shift
       ;;
     -d | --debug)
-      debug=1
+      DEBUG=1
       shift
       ;;
     -h | --help)
diff --git a/url-status-check b/url-status-check
--- a/url-status-check
+++ b/url-status-check
@@ -5,6 +5,9 @@
 
 set -euo pipefail
 
+# Set terminal type for proper color support
+export TERM=xterm-256color
+
 # Main function wrapper
 main() {
   # Check if common-functions exists
@@ -30,21 +33,21 @@ show_usage() {
   echo
   echo "Check HTTP status codes and redirects"
   echo
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Options:${FORMAT_RESET}"
-  log_usage_options_line "Maximum number of redirects to follow (default: $DEFAULT_MAX_REDIRECTS)" "-r" "--max-redirects NUM"
-  log_usage_options_line "Request timeout (default: $DEFAULT_TIMEOUT)" "-t" "--timeout SECONDS"
-  log_usage_options_line "User agent string (default: Mozilla/5.0...)" "-u" "--user-agent STRING"
-  log_usage_options_line "HTTP method (default: GET)" "-m" "--method METHOD"
-  log_usage_options_line "Add custom header (can be used multiple times)" "-H" "--header HEADER"
-  log_usage_options_line "Cookie string" "-c" "--cookies STRING"
+  log_header "Options"
+  log_usage_options_line "Maximum number of redirects to follow (default: $DEFAULT_MAX_REDIRECTS)" "-r" "--max-redirects <NUM>"
+  log_usage_options_line "Request timeout (default: $DEFAULT_TIMEOUT)" "-t" "--timeout <SECONDS>"
+  log_usage_options_line "User agent string (default: Mozilla/5.0...)" "-u" "--user-agent <STRING>"
+  log_usage_options_line "HTTP method (default: GET)" "-m" "--method <METHOD>"
+  log_usage_options_line "Add custom header (can be used multiple times)" "-H" "--header <HEADER>"
+  log_usage_options_line "Cookie string" "-c" "--cookies <STRING>"
   log_usage_options_line "Disable SSL certificate verification" "-k" "--insecure"
   log_usage_options_line "Don't follow redirects" "-f" "--no-follow"
   log_usage_options_line "Enable parallel processing" "-p" "--parallel"
-  log_usage_options_line "Maximum parallel requests (default: 5)" "-P" "--max-parallel NUM"
-  log_usage_options_line "Output format: text, json, csv (default: text)" "-F" "--format FORMAT"
+  log_usage_options_line "Maximum parallel requests (default: 5)" "-P" "--max-parallel <NUM>"
+  log_usage_options_line "Output format: text, json, csv (default: text)" "-F" "--format <FORMAT>"
   log_usage_options_line "Show this help message" "-h" "--help"
   echo
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Examples:${FORMAT_RESET}"
+  log_header "Examples"
   log_usage_example_line "$0 https://example.com"
   log_usage_example_line "$0 -r 10 -t 30 https://example.com"
   log_usage_example_line "$0 -m POST -H \"Content-Type: application/json\" https://api.example.com"
@@ -73,67 +76,67 @@ max_parallel=5
 
 # Function to get status color
 get_status_color() {
-  local code="$1"
-  if [[ "$code" -lt 300 ]]; then
-    echo "$COLOR_GREEN"
-  elif [[ "$code" -lt 400 ]]; then
-    echo "$COLOR_YELLOW"
-  elif [[ "$code" -lt 500 ]]; then
-    echo "$COLOR_RED"
+  local _code="$1"
+  if [[ "$_code" -lt 300 ]]; then
+    echo -e "$(styler text "GREEN")"
+  elif [[ "$_code" -lt 400 ]]; then
+    echo -e "$(styler text "YELLOW")"
+  elif [[ "$_code" -lt 500 ]]; then
+    echo -e "$(styler text "RED")"
   else
-    echo "$COLOR_PURPLE"
+    echo -e "$(styler text "PURPLE")"
   fi
 }
 
 # Function to check URL status
 check_url() {
-  local url="$1"
-  local redirect_count="${2:-0}"
-  local original_url="${3:-}"
+  local _url="$1"
+  local _redirect_count="${2:-0}"
+  local _original_url="${3:-}"
 
   if [[ -z "$original_url" ]]; then
     original_url="$url"
   fi
 
   # Build curl command
-  local curl_cmd="curl -s -i -k --max-time $timeout"
+  local _curl_cmd="curl -s -i -k --max-time $timeout"
 
   # Add user agent
-  curl_cmd="$curl_cmd -H 'User-Agent: $user_agent'"
+  _curl_cmd="$_curl_cmd -H 'User-Agent: $user_agent'"
 
   # Add custom headers
   for header in "${headers[@]}"; do
-    curl_cmd="$curl_cmd -H '$header'"
+    _curl_cmd="$_curl_cmd -H '$header'"
   done
 
   # Add cookies
   if [[ -n "$cookies" ]]; then
-    curl_cmd="$curl_cmd -H 'Cookie: $cookies'"
+    _curl_cmd="$_curl_cmd -H 'Cookie: $cookies'"
   fi
 
   # Add method
   if [[ "$method" != "GET" ]]; then
-    curl_cmd="$curl_cmd -X $method"
+    _curl_cmd="$_curl_cmd -X $method"
   fi
 
   # Add SSL verification
   if [[ "$ssl_verify" == "0" ]]; then
-    curl_cmd="$curl_cmd -k"
+    _curl_cmd="$_curl_cmd -k"
   fi
 
   # Add redirect handling
   if [[ "$follow_redirects" == "0" ]]; then
-    curl_cmd="$curl_cmd --max-redirs 0"
+    _curl_cmd="$_curl_cmd --max-redirs 0"
   else
-    curl_cmd="$curl_cmd --max-redirs $max_redirects"
+    _curl_cmd="$_curl_cmd --max-redirs $max_redirects"
   fi
 
   # Add output format
-  curl_cmd="$curl_cmd -o /dev/null --write-out '%{http_code}|%{redirect_url}|%{time_total}|%{size_download}|%{url_effective}'"
+  _curl_cmd="$_curl_cmd -o /dev/null --write-out '%{http_code}|%{redirect_url}|%{time_total}|%{size_download}|%{url_effective}'"
 
   # Execute curl command
-  local response
-  if ! response=$(eval "$curl_cmd '$url'" 2>/dev/null); then
+  local _response
+  if ! response=$(eval "$_curl_cmd '$url'" 2>/dev/null); then
     log_error "Failed to check URL: $url"
     return 1
   fi
@@ -142,7 +145,7 @@ check_url() {
   IFS='|' read -r response_code redirect_url time_total size_download url_effective <<<"$response"
 
   # Get status color
-  local color
+  local _color
   color=$(get_status_color "$response_code")
 
   # Output results based on format
@@ -156,23 +159,23 @@ check_url() {
   "redirect_url": "$redirect_url",
   "response_time": $time_total,
   "content_length": $size_download,
-  "redirect_count": $redirect_count
+  "redirect_count": $_redirect_count
 }
 EOF
     ;;
   "csv")
-    echo "$original_url,$url_effective,$response_code,$redirect_url,$time_total,$size_download,$redirect_count"
+    echo "$original_url,$url_effective,$response_code,$redirect_url,$time_total,$size_download,$_redirect_count"
     ;;
   *)
     # Text format
     printf "%-60s " "$url"
-    printf "[${color}%3s${FORMAT_RESET}] " "$response_code"
+    printf "[${color}%3s$(styler reset)] " "$response_code"
     if [[ -n "$redirect_url" ]]; then
       printf "→ %s " "$redirect_url"
     fi
-    printf "(${time_total}s, ${size_download} bytes)"
-    if [[ "$redirect_count" -gt 0 ]]; then
-      printf " [%d redirects]" "$redirect_count"
+    printf "(%ss, %s bytes)" "$time_total" "$size_download"
+    if [[ "$_redirect_count" -gt 0 ]]; then
+      printf " [%d redirects]" "$_redirect_count"
     fi
     echo
     ;;
@@ -180,26 +183,26 @@ EOF
 
   # Follow redirects if enabled and status is 3xx
   if [[ "$follow_redirects" == "1" && "$response_code" -ge 300 && "$response_code" -lt 400 && -n "$redirect_url" ]]; then
-    if [[ "$redirect_count" -ge "$max_redirects" ]]; then
+    if [[ "$_redirect_count" -ge "$max_redirects" ]]; then
       log_warning "Maximum redirects exceeded for $original_url"
       return 1
     fi
 
     # Recursively check redirect URL
-    check_url "$redirect_url" $((redirect_count + 1)) "$original_url"
+    check_url "$redirect_url" $((_redirect_count + 1)) "$original_url"
   fi
 }
 
 # Function to process URLs from file
 process_urls_from_file() {
-  local file="$1"
+  local _file="$1"
 
-  if [[ ! -f "$file" ]]; then
-    log_error "File not found: $file"
+  if [[ ! -f "$_file" ]]; then
+    log_error "File not found: $_file"
     return 1
   fi
 
-  log_info "Processing URLs from file: $file"
+  log_info "Processing URLs from file: $_file"
 
   # Add CSV header if output format is CSV
   if [[ "$output_format" == "csv" ]]; then
@@ -221,23 +224,23 @@ process_urls_from_file() {
     # Check URL
     check_url "$line"
 
-  done <"$file"
+  done <"$_file"
 }
 
 # Function to process URLs in parallel
 process_urls_parallel() {
-  local urls=("$@")
-  local pids=()
-  local results=()
+  local _urls=("$@")
+  local _pids=()
+  local _results=()
 
-  log_info "Processing ${#urls[@]} URLs in parallel (max: $max_parallel)"
+  log_info "Processing ${#_urls[@]} URLs in parallel (max: $max_parallel)"
 
-  for url in "${urls[@]}"; do
+  for url in "${_urls[@]}"; do
     # Wait if we've reached max parallel processes
-    while [[ ${#pids[@]} -ge $max_parallel ]]; do
-      for i in "${!pids[@]}"; do
-        if ! kill -0 "${pids[$i]}" 2>/dev/null; then
-          unset pids[$i]
+    while [[ ${#_pids[@]} -ge $max_parallel ]]; do
+      for i in "${!_pids[@]}"; do
+        if ! kill -0 "${_pids[$i]}" 2>/dev/null; then
+          unset "${_pids[$i]}"
         fi
       done
       sleep 0.1
@@ -245,11 +248,11 @@ process_urls_parallel() {
 
     # Start background process
     check_url "$url" &
-    pids+=($!)
+    _pids+=($!)
   done
 
   # Wait for all processes to complete
-  for pid in "${pids[@]}"; do
+  for pid in "${_pids[@]}"; do
     wait "$pid"
   done
 }
diff --git a/wordpress-update b/wordpress-update
--- a/wordpress-update
+++ b/wordpress-update
@@ -5,6 +5,9 @@
 
 set -euo pipefail
 
+# Set terminal type for proper color support
+export TERM=xterm-256color
+
 # Main function wrapper
 main() {
   # Check if common-functions exists
@@ -29,23 +32,23 @@ show_usage() {
   echo ""
   echo "Update WordPress installations safely"
   echo ""
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Options:${FORMAT_RESET}"
-  log_usage_options_line "WordPress version to install (default: $DEFAULT_WP_VERSION)" "-v" "--version VERSION"
-  log_usage_options_line "WordPress source directory path (default: current directory)" "-s" "--source PATH"
-  log_usage_options_line "Issue/ticket number for git commit" "-i" "--issue ISSUE"
+  log_header "Options"
+  log_usage_options_line "WordPress version to install (default: $DEFAULT_WP_VERSION)" "-v" "--version <VERSION>"
+  log_usage_options_line "WordPress source directory path (default: current directory)" "-s" "--source <PATH>"
+  log_usage_options_line "Issue/ticket number for git commit" "-i" "--issue <ISSUE>"
   log_usage_options_line "Skip creating backup before update" "-b" "--no-backup"
   log_usage_options_line "Skip git operations" "-g" "--no-git"
   log_usage_options_line "Show what would be done without making changes" "-n" "--dry-run"
   log_usage_options_line "Force update even if version is the same" "-f" "--force"
   log_usage_options_line "Show this help message" "-h" "--help"
   echo ""
-  echo -e "${FORMAT_BOLD}${COLOR_YELLOW}Examples:${FORMAT_RESET}"
+  log_header "Examples"
   log_usage_example_line "$0 --version 6.4.2 --source /var/www/html"
   log_usage_example_line "$0 --version latest --issue \"WP-123\""
   log_usage_example_line "$0 --dry-run --version 6.4.1"
   log_usage_example_line "$0 --no-backup --no-git --version 6.4.2"
   echo ""
-  echo "Notes:"
+  log_header "Notes"
   echo "  - Always backup your WordPress installation before updating"
   echo "  - The script will update core WordPress files only"
   echo "  - Plugins and themes are not affected"
@@ -76,11 +79,11 @@ force=0
 
 # Function to get current WordPress version
 get_current_wp_version() {
-  local docroot="$1"
-  local version_file="$docroot/wp-includes/version.php"
+  local _docroot="$1"
+  local _version_file="$_docroot/wp-includes/version.php"
 
-  if [[ -f "$version_file" ]]; then
-    grep "wp_version =" "$version_file" | cut -d"'" -f2
+  if [[ -f "$_version_file" ]]; then
+    grep "wp_version =" "$_version_file" | cut -d"'" -f2
   else
     echo "unknown"
   fi
@@ -88,127 +91,125 @@ get_current_wp_version() {
 
 # Function to get latest WordPress version
 get_latest_wp_version() {
-  local latest_version
-  if ! latest_version=$(curl -s "https://api.wordpress.org/core/version-check/1.7/" | grep -o '"version":"[^"]*"' | head -1 | cut -d'"' -f4); then
+  local _latest_version
+  if ! _latest_version=$(curl -s "https://api.wordpress.org/core/version-check/1.7/" | grep -o '"version":"[^"]*"' | head -1 | cut -d'"' -f4); then
     log_error "Failed to get latest WordPress version"
     return 1
   fi
-  echo "$latest_version"
+  echo "$_latest_version"
 }
 
 # Function to create backup
 create_backup() {
-  local docroot="$1"
-  local backup_dir="${docroot}/../wp-backup-$(date +%Y%m%d-%H%M%S)"
+  local _docroot="$1"
+  local _backup_dir
+  _backup_dir="${_docroot}/../wp-backup-$(date +%Y%m%d-%H%M%S)"
 
-  log_info "Creating backup to: $backup_dir"
+  log_info "Creating backup to: $_backup_dir"
 
   if [[ "$dry_run" == "1" ]]; then
-    log_info "DRY RUN: Would create backup at $backup_dir"
+    log_info "DRY RUN: Would create backup at $_backup_dir"
     return 0
   fi
 
-  mkdir -p "$backup_dir"
+  mkdir -p "$_backup_dir"
 
   # Copy WordPress core files
   for dir in "${WP_DIRECTORIES[@]}"; do
-    if [[ -d "$docroot/$dir" ]]; then
-      cp -r "$docroot/$dir" "$backup_dir/"
+    if [[ -d "$_docroot/$dir" ]]; then
+      cp -r "$_docroot/$dir" "$_backup_dir/"
     fi
   done
 
   for file in "${WP_FILES[@]}"; do
-    if [[ -f "$docroot/$file" ]]; then
-      cp "$docroot/$file" "$backup_dir/"
+    if [[ -f "$_docroot/$file" ]]; then
+      cp "$_docroot/$file" "$_backup_dir/"
     fi
   done
 
-  log_success "Backup created: $backup_dir"
+  log_success --status "$_backup_dir" "Backup created"
 }
 
 # Function to download WordPress
 download_wordpress() {
-  local version="$1"
-  local download_url="https://wordpress.org/wordpress-${version}.zip"
-  local temp_dir="/tmp/wp-update-$$"
-  local zip_file="$temp_dir/wordpress.zip"
+  local _version="$1"
+  local _zip_file="$2"
+  local _download_url="https://wordpress.org/wordpress-${_version}.zip"
 
-  log_info "Downloading WordPress $version from: $download_url"
+  log_info "Downloading WordPress $_version from: $_download_url"
 
   if [[ "$dry_run" == "1" ]]; then
-    log_info "DRY RUN: Would download from $download_url"
+    log_info "DRY RUN: Would download from $_download_url"
     return 0
   fi
 
-  mkdir -p "$temp_dir"
-
-  if ! curl -L -o "$zip_file" "$download_url"; then
-    log_error "Failed to download WordPress $version"
+  if ! curl -L -o "$_zip_file" "$_download_url"; then
+    log_error "Failed to download WordPress $_version"
     return 1
   fi
 
-  log_success "WordPress $version downloaded successfully"
-  echo "$zip_file"
+  log_success --status  "$_zip_file" "WordPress %s downloaded successfully" "$_version"
 }
 
 # Function to extract WordPress
 extract_wordpress() {
-  local zip_file="$1"
-  local extract_dir="$(dirname "$zip_file")/wordpress"
+  local _zip_file="$1"
+  local _extract_dir
+  _extract_dir="$(dirname "$_zip_file")/wordpress"
 
   log_info "Extracting WordPress archive"
 
   if [[ "$dry_run" == "1" ]]; then
-    log_info "DRY RUN: Would extract to $extract_dir"
+    log_info "DRY RUN: Would extract to $_extract_dir"
     return 0
   fi
 
-  if ! unzip -q "$zip_file" -d "$(dirname "$zip_file")"; then
+  if ! unzip -q "$_zip_file" -d "$(dirname "$_zip_file")"; then
     log_error "Failed to extract WordPress archive"
     return 1
   fi
 
   log_success "WordPress extracted successfully"
-  echo "$extract_dir"
+  echo "$_extract_dir"
 }
 
 # Function to update WordPress files
 update_wordpress_files() {
-  local docroot="$1"
-  local extract_dir="$2"
+  local _docroot="$1"
+  local _extract_dir="$2"
 
   log_info "Updating WordPress core files"
 
   # Remove old core files
   for dir in "${WP_DIRECTORIES[@]}"; do
-    if [[ -d "$docroot/$dir" ]]; then
+    if [[ -d "$_docroot/$dir" ]]; then
       if [[ "$dry_run" != "1" ]]; then
-        rm -rf "$docroot/$dir"
+        rm -rf "$_docroot/$dir"
       fi
     fi
   done
 
   for file in "${WP_FILES[@]}"; do
-    if [[ -f "$docroot/$file" ]]; then
+    if [[ -f "$_docroot/$file" ]]; then
       if [[ "$dry_run" != "1" ]]; then
-        rm -f "$docroot/$file"
+        rm -f "$_docroot/$file"
       fi
     fi
   done
 
   # Copy new core files
   for dir in "${WP_DIRECTORIES[@]}"; do
-    if [[ -d "$extract_dir/$dir" ]]; then
+    if [[ -d "$_extract_dir/$dir" ]]; then
       if [[ "$dry_run" != "1" ]]; then
-        cp -r "$extract_dir/$dir" "$docroot/"
+        cp -r "$_extract_dir/$dir" "$_docroot/"
       fi
     fi
   done
 
   for file in "${WP_FILES[@]}"; do
-    if [[ -f "$extract_dir/$file" ]]; then
+    if [[ -f "$_extract_dir/$file" ]]; then
       if [[ "$dry_run" != "1" ]]; then
-        cp "$extract_dir/$file" "$docroot/"
+        cp "$_extract_dir/$file" "$_docroot/"
       fi
     fi
   done
@@ -218,9 +219,9 @@ update_wordpress_files() {
 
 # Function to commit to git
 commit_to_git() {
-  local docroot="$1"
-  local version="$2"
-  local issue="$3"
+  local _docroot="$1"
+  local _version="$2"
+  local _issue="$3"
 
   if [[ "$git_commit" != "1" ]]; then
     return 0
@@ -240,18 +241,18 @@ commit_to_git() {
   fi
 
   # Add changes
-  git add "$docroot"
+  git add "$_docroot"
 
   # Create commit message
-  local commit_message="Upgrade to WordPress $version"
-  if [[ -n "$issue" ]]; then
-    commit_message="$commit_message
+  local _commit_message="Upgrade to WordPress $_version"
+  if [[ -n "$_issue" ]]; then
+    _commit_message="$_commit_message
 
-Issue: $issue"
+Issue: $_issue"
   fi
 
   # Commit changes
-  if ! git commit -m "$commit_message"; then
+  if ! git commit -m "$_commit_message"; then
     log_warning "Git commit failed or no changes to commit"
   else
     log_success "Changes committed to git"
@@ -260,9 +261,9 @@ Issue: $issue"
 
 # Function to cleanup temporary files
 cleanup() {
-  local temp_dir="$1"
-  if [[ -n "$temp_dir" && -d "$temp_dir" ]]; then
-    rm -rf "$temp_dir"
+  local _temp_dir="$1"
+  if [[ -n "$_temp_dir" && -d "$_temp_dir" ]]; then
+    rm -rf "$_temp_dir"
   fi
 }
 
@@ -316,22 +317,16 @@ parse_arguments() {
 # Main function
 wordpress_main() {
   log_title "WordPress Update"
-
-  # Parse arguments
   parse_arguments "$@"
-
-  # Check dependencies
   check_dependencies curl git
-
-  # Validate WordPress directory
   if ! validate_wp_directory "$wp_source"; then
-    exit 1
+    exit
   fi
 
   # Get current version
-  local current_version
-  current_version=$(get_current_wp_version "$wp_source")
-  log_info "Current WordPress version: $current_version"
+  local _current_version
+  _current_version=$(get_current_wp_version "$wp_source")
+  log_info "Current WordPress version: $_current_version"
 
   # Handle "latest" version
   if [[ "$wp_version" == "latest" ]]; then
@@ -340,7 +335,7 @@ wordpress_main() {
   fi
 
   # Check if update is needed
-  if [[ "$current_version" == "$wp_version" && "$force" != "1" ]]; then
+  if [[ "$_current_version" == "$wp_version" && "$force" != "1" ]]; then
     log_info "WordPress is already at version $wp_version"
     if [[ "$force" != "1" ]]; then
       log_info "Use --force to update anyway"
@@ -351,7 +346,7 @@ wordpress_main() {
   # Confirm update
   if [[ "$dry_run" != "1" ]]; then
     echo
-    log_warning "This will update WordPress from $current_version to $wp_version"
+    log_warning "This will update WordPress from $_current_version to $wp_version"
     log_warning "Make sure you have a backup before proceeding!"
     echo
     read -p "Do you want to continue? (y/N): " -n 1 -r
@@ -368,24 +363,26 @@ wordpress_main() {
   fi
 
   # Download WordPress
-  local zip_file
-  zip_file=$(download_wordpress "$wp_version")
+  local _temp_dir="/tmp/wp-update-$$"
+  mkdir -p "$_temp_dir"
+  local _zip_file="$_temp_dir/wordpress.zip"
+  download_wordpress "$wp_version" "$_zip_file"
 
   # Extract WordPress
-  local extract_dir
-  extract_dir=$(extract_wordpress "$zip_file")
+  local _extract_dir
+  _extract_dir=$(extract_wordpress "$_zip_file")
 
   # Update WordPress files
-  update_wordpress_files "$wp_source" "$extract_dir"
+  update_wordpress_files "$wp_source" "$_extract_dir"
 
   # Commit to git
   commit_to_git "$wp_source" "$wp_version" "$issue_no"
 
   # Cleanup
-  cleanup "$(dirname "$zip_file")"
+  cleanup "$(dirname "$_zip_file")"
 
   # Final success message
-  log_success "WordPress updated successfully from $current_version to $wp_version"
+  log_success "WordPress updated successfully from $_current_version to $wp_version"
 
   if [[ "$dry_run" == "1" ]]; then
     log_info "This was a dry run - no actual changes were made"
